language: python
python:
    - 3.5
    - 3.6

before_install:
    - sudo apt-get update
    - sudo apt-get install texlive-latex-extra texlive-bibtex-extra
    - sudo apt-get install pdftk

script:
    - texhash
    - travis_wait ./create_project
